### PR TITLE
FCREPO-1403

### PR DESCRIPTION
**Pull request by ajs6f**
Using identifiers of the same character as other Fedora ontologies, move ResourceStatus into the correct namespace.

### CODE REVIEW

**Comment by acoburn** [comment]
I may be completely off base here, but when I convert this ontology to ntriples or turtle (both of which I find much easier to read than XML), I see that the properties and individuals are prefixed with `http://fedora.info/definitions/1/0/access/` and not `http://fedora.info/definitions/1/0/access/ObjState#`. In all the RDF/XML I've ever seen, I have always observed that in `rdf:about` and `rdf:resource` attributes, the URIs are fully qualified. I would recommend changing the serialization to use fully qualified URIs. At least by using hash prefixes, the namespace resolves properly, but as it is, it is not correct.

Also, if the ontology is `ObjState`, would it not make more sense if the filename was `ObjState.rdf` and not `objState.rdf`? I realize that there is a difference between the namespace and the location of the published resource, but that very minor discrepancy could lead to user errors.

**Comment by ajs6f** [comment]
Definitely true about the filename. I'll see if I can change that quickly. That's weird about the namespacing. By spec, relative URIs in RDF/XML are supposed to resolve against `xml:base`, including `rdf:about`. What did you use to convert?

**Comment by acoburn** [comment]
I used http://www.easyrdf.org/converter -- top of the list in google. The only reason I used that was because I know the hydra folks are going to use RDF.rb's `vocab-fetch` utility, and that didn't find the properties and individuals for the provided namespace (it did when you prefixed them with `#`).

**Comment by ajs6f** [comment]
This is weird, Jena `riot` shows the same thing. Why that's weird is that the ns `http://fedora.info/definitions/1/0/access/` doesn't explicitly appear. I'm going to figure out why that's happening. I have seen relative URIs used in RDF/XML with some frequency, and it shouldn't be that hard.

**Comment by ajs6f** [comment]
https://www.w3.org/TR/2014/REC-rdf-syntax-grammar-20140225/#section-Syntax-ID-xml-base

"The base URI applies to all RDF/XML attributes that deal with IRIs which are rdf:about, rdf:resource, rdf:ID and rdf:datatype."

**Comment by acoburn** [comment]
I believe what you want is `rdf:ID` instead of the various `rdf:about` attributes (except for the first one, where you already have a fully qualified URI).

**Comment by acoburn** [comment]
While changing the attributes to rdf:ID works for scoping the property and class definitions, it still leaves the rdf:type/rdfs:range values as `<http://fedora.info/definitions/1/0/access/ResourceStatus>`, which is clearly wrong.

**Comment by awoods** [comment]
It seems like the simplest solution is to use fully qualified URIs throughout.

**Comment by ajs6f** [comment]
No, I don't want `rdf:ID`. I want the parsing to work properly. There's not much doubt in my mind now that `rdf:about` should resolve against `xml:base`, based on that spec section. I don't want to use FQ URIs because that is literally the opposite of DRY.

**Comment by ajs6f** [comment]
Y'all can edit this PR to use FQ URIs if you want to merge it that way. Otherwise, when I have a chance I will take a look at why relative URIs aren't working correctly.

**Comment by acoburn** [comment]
I'm all in favor of getting the parsing to work properly with relative URIs and `xml:base` (given the spec document), but I'm more in favor of simply getting it to work properly. I'm also in no rush on this.

**Comment by awoods** [comment]
@ajs6f or @acoburn, If you are ok with the PR against this PR, please merge it:
https://github.com/fcrepo4-exts/fcrepo-extra-ontologies/pull/4

...we can then move forward with publishing this ontology.

**Pull request merged**
