### PR TITLE
Consolidate ontologies:

### PR DESCRIPTION
**Pull request by awoods**
- audit
- indexing
- objState

Partial resolution of https://jira.duraspace.org/browse/FCREPO-2030

### CODE REVIEW

**Comment by acoburn** [comment]
But where is the audit ontology?

**Comment by acoburn** [comment]
oh, nevermind -- I see what you did.

**Comment by acoburn** [comment]
@ruebot I'd say that, unlike source code history, the history of ontologies/vocabularies is adequately preserved in their published versions. These ontologies are also incredibly small and I am not sure that any git history would be all that interesting or useful.

**Comment by awoods** [comment]
I am fine letting the published versions speak for themselves.

**Pull request merged**
